name: scroller
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_auth: ^3.3.20
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  image_picker: ^0.8.5+3
  video_player: ^2.4.5
  video_compress: ^3.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  timeago: ^3.2.0
  loading_animation_widget: ^1.2.0+2
  flutter: 
    sdk: flutter
  shimmer: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/image/

    
  fonts:
    - family: Customicon
      fonts:
        - asset: assets/fonts/Customicon.ttf  
        - asset: assets/image/postupload.png
        - asset: assets/image/search.png